[book]
authors = ["Axos Core Contributors"]
language = "en"
multilingual = false
src = "docs"
title = "Axos Book"
description = "Detailed documentation and specifications for the Axos derivation pipeline."

[output.html]
git-repository-url = "https://github.com/refcell/axos"
default-theme = "ayu"
no-section-label = true

[output.html.fold]
enable = true
level = 1

[build]
build-dir = "target/book"

[preprocessor.index]

[preprocessor.links]
